name: "Run GAP test suite"
description: "Runs the testintall.g or the teststandard.g script to test the GAP installation"
inputs:
  ONLY_NEEDED:
    description: "Only load necessary packages, not suggested ones, prior to testing"
    required: false
    default: false
  COMPLETE:
    description: "Whether to use testinstall.g or the more complete (but slower) teststandard.g"
    required: false
    default: false
defaults:
  run:
    shel:: bash

runs:
  using: "composite"
  steps:
  
    - name: "Run GAP test suite"
      shell: bash
      run: |
        set -ex
       
        # Add package to the custom GAP root
        ln -f -s $PWD /tmp/gaproot/pkg/
        
        # Add extra flags
        GAP="gap ${{ inputs.GAP_FLAGS }}"
        
        $GAP <<GAPInput
        
        # Decide which test file should be used
        if ${{ inputs.COMPLETE }} then
            testFile := "teststandard.g";
        else
            testFile := "testinstall.g";
        fi;
        
        GAP_TESTFILE := Filename( DirectoriesLibrary( "tst" ), testFile );
        
        Read( "PackageInfo.g" );
        info := GAPInfo.PackageInfoCurrent;
        
        # Load the package with debug info
        SetInfoLevel( InfoPackageLoading, PACKAGE_DEBUG );
        SetPackagePath( info.PackageName, "/tmp/gaproot/pkg/$(basename $PWD)" );
        if ${{ inputs.ONLY_NEEDED }} then
            LoadPackage( info.PackageName : OnlyNeeded );
        else
            LoadPackage( info.PackageName );
        fi;
        SetInfoLevel( InfoPackageLoading, PACKAGE_ERROR );
        
        Read( GAP_TESTFILE );
        GAPInput
